### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by NabeelahB** [debrouwere/facebook-insights#5]
Hi,
I am trying to authenticate by sending the client id and secret. the authentication browser opens and shows successful and then this error occurs
`>>> # this will launch a web browser to authenticate
... pages = fi.authenticate(
...     client_id='1113595855373558',
...     client_secret='91f0254c1534966e8cf9ddecc1c36d1b',
...     )
Authentication flow completed. You may close the browser tab.
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "C:\Users\nabeelah.bijapur\Documents\Anaconda3\lib\site-packages\facebookinsights\__init__.py", line 35, in authenticate
    return [graph.Page(token) for token in tokens]
  File "C:\Users\nabeelah.bijapur\Documents\Anaconda3\lib\site-packages\facebookinsights\__init__.py", line 35, in <listcomp>
    return [graph.Page(token) for token in tokens]
  File "C:\Users\nabeelah.bijapur\Documents\Anaconda3\lib\site-packages\facebookinsights\graph.py", line 366, in __init__
    self.username = data['username']
KeyError: 'username'`

The same thing occurs when I pass the access_token.
Can you point out the issue.
Regards,

**Comment by obenkiki** [comment]
Hello Nabeelah, 

Im facing the same issue. Did you find a solution?

Best

**Comment by avislavkin** [comment]
Fix
graph.py line 366
#self.username = data['username']
